### ISSUE TITLE
dreams s3 storage should move to google cloud storage

### ISSUE THREAD

**Issue by OriHoch** [Midburn/midburn-k8s#22]
## TODO
* copy the existing buckets from S3 to google cloud storage (can use `gsutil` from the [google cloud sdk](https://cloud.google.com/sdk/downloads))
* modify the [dreams papertrail configuration](https://github.com/Midburn/Dreams/blob/29b61eef6962760b1c59636ab9fbf8a7a0d3f91d/config/environments/production.rb#L86) and the [dreams chart](https://github.com/Midburn/midburn-k8s/tree/master/charts-external/dreams) to conditionally support AWS or google storage
* deploy with google storage

**Comment by elad-lachmi** [comment]
We are currently using S3 storage for many services in the K8S cluster.
We can revisit this if we ever want to migrate away from AWS.
