### ISSUE TITLE
investigate problem with downloading large file from spark pod

### ISSUE THREAD

**Issue by OriHoch** [Midburn/midburn-k8s#27]
### reproduction
* start a port-forward to the spark pod (to eliminate load balancer / service / traefik / nginx / other problems)
  * `kubectl port-forward spark-fb5d9cf5-x7wsj 3000`
* access the port-forwarded spark at http://localhost:3000
* log-in with admin user
* click on ניהול קבצים and download all

#### expected
* download the camp files zip

#### actual
![image](https://user-images.githubusercontent.com/1198854/36970597-ca34a986-2071-11e8-80bd-02cf4fb73491.png)

**Comment by OriHoch** [comment]
@elad-lachmi does it work with a local spark instance?
it looks like a limitation of node..

**Comment by elad-lachmi** [comment]
Yes, it works perfectly in a local environment

**Comment by OriHoch** [comment]
@elad-lachmi with 100MB zip file?

**Comment by OriHoch** [comment]
@elad-lachmi did you test with local node or using docker-compose?
please provide some more details about how you tested, it will be very helpful to debug the issue

**Comment by elad-lachmi** [comment]
I ran the node project without NLB or proxy and the download went fine. 

I didn’t get around to testing it with docker-compose behind nginx or traefik

I can try that tonight.

**Comment by elad-lachmi** [comment]
Yes, I targeted the prod. bucket

**Comment by OriHoch** [comment]
I wrote how to do it manually here
Midburn/spark#707
if this manual procedure works well, I don't see a reason to fix the spark problems
unless I missed something and this manual package is not sufficient

wtill worth to investigate this problem.. but lower priority I guess

**Comment by elad-lachmi** [comment]
The code streams directly:
S3 stream --> Archiver stream --> express.js response stream to client
Byte by byte.
