### ISSUE TITLE
Tagging services and servers in kubernetes for budget follow up

### ISSUE THREAD

**Issue by pandamichal** [Midburn/midburn-k8s#48]
In order to plan the budget for Midburn 2019, we need to know how much money each system (Dreams, Spark etc) costs us. 
The tagging in Amazon is easy, we need help with tagging the systems that run on the Kubernetes to create a cost report each month. 
@OriHoch  can you help us with that?

Thanks!

Panda.

**Comment by OriHoch** [comment]
Most of the billable resources in kubernetes are shared between all the projects, so the billing cannot be separated like we did in Amazon
