### ISSUE TITLE
loomio - config login providers

### ISSUE THREAD

**Issue by dyeote** [Midburn/midburn-k8s#49]
-add Google as login provider for talk.midburn.org
-add Facebook as login provider for talk.midburn.org
-add create password prompt for new users registering to the forum (instead of repeated email authentication with each login)

https://github.com/loomio/loomio-deploy/blob/master/configure_login_providers.md

**Comment by elad-lachmi** [comment]
Both Facebook and Google OAuth providers have been implemented.
Creating a password can be done through the user profile page. Most people will likely use either of the social logins. For the few holdouts, they can go into the user profile page and create a password for their account.
