### ISSUE TITLE
Dreams Repository has heroko environments that needs deleting

### ISSUE THREAD

**Issue by enoodle** [Midburn/midburn-k8s#66]
Please remove heroku from Dreams repository

**Comment by enoodle** [comment]
@elad-lachmi

**Comment by elad-lachmi** [comment]
I can't find any connection between the current repository and the Heroku deployment and Travis also doesn't look to be running anything related to Heroku.
I also don't know Ruby at all, so if this happens somewhere inside the Ruby code, I have no idea where.

I'm closing this issue. If you still have an issue and have something more specific for me to do, please feel free to reopen.
Sorry, that's all I can do at this point.
